config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "welcome#index"
  get "my_portfolio", to: "users#my_portfolio"
  post "search_stock", to: "stocks#search"
  get "my_friends", to: "users#my_friends"
  post "search_friend", to: "users#search"
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :user_stocks
    has_many :users, through: :user_stocks

    validates :name, :ticker, presence: true

    def self.new_lookup(ticker_symbol)
        client = IEX::Api::Client.new(
            publishable_token: Rails.application.credentials.iex_client[:publishable_token],
            secret_token: Rails.application.credentials.iex_client[:secret_token],
            endpoint: 'https://cloud.iexapis.com/v1'
        )

        begin
            new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
        rescue => exception
            return nil
        end
    end

    def self.check_db(ticker_symbol)
        where(ticker: ticker_symbol).first
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many  :user_stocks
  has_many  :stocks, through: :user_stocks
  has_many  :friendships
  has_many  :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  def under_stock_limit?
    stocks.count < 10
  end

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    param.downcase!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} LIKE ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject {|user| user.id == self.id}
  end

  def not_friends_with?(friend_id)
    !self.friends.where(id: friend_id).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    def create
        friend = User.find(params[:friend])
        current_user.friendships.build(friend_id: friend.id)
        if current_user.save
            flash[:notice] = "Friend was successfully added"
        else
            flash[:alert] = "There was something wrong with the friend request"
        end
        redirect_to my_friends_path
    end

    def destroy
        friendship = current_user.friendships.where(friend_id: params[:id]).first
        friendship.destroy
        flash[:notice] = "Friend was successfully removed"
        redirect_to my_friends_path
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    def search
        if params[:stock].present?
            @stock = Stock.new_lookup(params[:stock])

            if @stock
                render turbo_stream: turbo_stream.replace('results_turbo_stream', partial: 'users/result')
            else 
                flash.now[:alert] = "Please enter a valid symbol to search"
                render turbo_stream: turbo_stream.replace('results_turbo_stream', partial: 'users/result')
            end
        else
            flash.now[:alert] = "Please enter a symbol to search"
            render turbo_stream: turbo_stream.replace('results_turbo_stream', partial: 'users/result')
        end
    end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
    def create
        stock = Stock.check_db(params[:ticker])
        if stock.blank?
            stock = Stock.new_lookup(params[:ticker])
            stock.save
        end
        @user_stock = UserStock.create(user: current_user, stock: stock)
        flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio"
        redirect_to my_portfolio_path
    end

    def destroy
        stock = Stock.find(params[:id])
        user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
        user_stock.destroy
        flash[:notice] = "#{stock.ticker} was successfully removed from portfolio"
        redirect_to my_portfolio_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

  def my_portfolio
    @user = current_user
    if user_signed_in?
      @tracked_stocks = current_user.stocks
    else
      @tracked_stocks = []
    end
  end

  def my_friends
    @friends = current_user.friends
  end

  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if !@friends.empty?
        render turbo_stream: turbo_stream.replace('results_turbo_stream', partial: 'friends/result')
      else 
        flash.now[:alert] = "Not user found with that name or email"
        render turbo_stream: turbo_stream.replace('results_turbo_stream', partial: 'friends/result')
      end
    else
        flash.now[:alert] = "Please enter a symbol to search"
        render turbo_stream: turbo_stream.replace('results_turbo_stream', partial: 'friends/result')
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    before_action :authenticate_user!
    
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_list.html.erb
<div class="row">
    <div class="col-9">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th scope="col">
                        Email
                    </th>
                    <th scope="col">
                        First Name
                    </th>
                    <th scope="col">
                        Last Name
                    </th>
                    <th scope="col">
                        Actions
                    </th>
                </tr>
            </thead>

            <tbody>
                <% @friends.each do |friend| %>
                    <tr>
                        <td>
                            <%= friend.email %>
                        </td>
                        <td>
                            <%= friend.first_name %>
                        </td>
                        <td>
                            <%= friend.last_name %>
                        </td>
                        <td>
                            <%= link_to 'View Profile',
                            user_path(friend),
                            class: "btn btn-sm btn-success"
                            %>
                            
                            <%= link_to 'Stop Following',
                            friendship_path(friend),
                            class: "btn btn-sm btn-warning",
                            data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }
                            %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/friends/_result.html.erb
<%= turbo_frame_tag 'results_turbo_stream' do %>
    <%= render 'layouts/messages' %>

    <% if @friends && !@friends.empty? %>
        <% @friends.each do |friend| %>
            <div class="card my-2 me-2">
                <div class="card-header">
                        Friend
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <strong>Name:</strong> <%= friend.full_name %>
                        </li>
                        <li class="list-group-item">
                            <strong>Email:</strong> <%= friend.email %>
                        </li>

                        <li class="list-group-item d-flex align-items-center">
                            <%= link_to 'View profile', user_path(friend), data: { turbo: false },class: "btn btn-sm btn-success me-2" %>
                            <% if current_user.not_friends_with?(friend) %>
                                <%= button_to 'Follow friend?', 
                                friendships_path(friend: friend),
                                data: { turbo: false, turbo_method: :post }, 
                                class: 'btn btn-sm btn-warning ms-auto' %>
                            <% else %>
                                <span class="badge bg-secondary">
                                    You are friends
                                </span>
                            <% end %>
                        </li>
                    </ul>
                </div>
            </div>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/_messages.html.erb
<div class="my-3">
    <% if notice %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <%= notice %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <% end %>
    
    <% if alert %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <%= alert %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <% end %>
</div>  
<% flash.clear %>  
    

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <%= link_to "FinanceTracker", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to "My Portfolio", my_portfolio_path, class: "nav-link #{'active' if request.path == my_portfolio_path}" %>
                </li>
                <li class="nav-item">
                    <%= link_to "My Friends", my_friends_path, class: "nav-link #{'active' if request.path == my_friends_path}" %>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Profile
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                                <%= fa_icon "edit", class: "me-1" %>
                                Edit Profile
                            <% end %>
                        </li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <% if user_signed_in? %>
                    <li class="nav-item d-flex align-items-center">
                        <%= fa_icon "user", class: "me-1" %>
                        <%= current_user.full_name %>
                    </li>

                    <li class="nav-item ms-1">
                        <%= link_to "Logout", destroy_user_session_path, class: "btn btn-danger", data: { turbo_method: :delete } %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
                    </li>
                    <li class="nav-item ms-1">
                        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success" %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrackingSocialMediaApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <div class="container">
      
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<% if @tracked_stocks.any? %>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Ticker</th>
                <th>Name</th>
                <th>Price</th>
                <th>Actions</th>
            </tr>
        </thead>

        <tbody>
            <% @tracked_stocks.each do |stock| %>
                <tr>
                    <td>
                        <%= stock.ticker %>
                    </td>
                    <td>
                        <%= stock.name %>
                    </td>
                    <td>
                        <%= stock.last_price %>
                    </td>
                    <td>
                        <% if current_user.id == @user.id %>
                            <%= link_to 'Remove', user_stock_path(user: current_user, id: stock.id), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

app/views/users/_result.html.erb
<%= turbo_frame_tag 'results_turbo_stream' do %>    
    <%= render 'layouts/messages' %>

    <% if @stock %>
        <div class="card my-2">
            <div class="card-header">
                Stocks
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <strong>Symbol:</strong> <%= @stock.ticker %>
                </li>
                <li class="list-group-item">
                    <strong>Name:</strong> <%= @stock.name %>
                </li>
                <li class="list-group-item">
                    <strong>Last Price:</strong> <%= @stock.last_price %>
                </li>
                <% if user_signed_in? && current_user.can_track_stock?(@stock.ticker) %>
                    <li class=list-group-item>
                        <%= button_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker), data: { turbo: false, turbo_method: :post }, class: 'btn btn-sm btn-success ms-auto' %>
                    </li>
                <% elsif user_signed_in? %>
                    <% if current_user.stocks.exists?(ticker: @stock.ticker) %>
                        <span class="badge bg-secondary">
                            You are tracking this stock
                        </span>
                    <% elsif current_user.under_stock_limit? %>
                        <span class="label label-default">
                            You are tracking the maximum number of stocks
                        </span>
                    <% end %>
                <% end %>
            </ul>
        </div>
    <% end %>
<% end %>

app/views/users/my_friends.html.erb
<div class="search-area">
    <h3> Friends </h3>

    <%= form_tag search_friend_path class: "form-inline" do %>
        <div class="form-group row">
            <div class="col-sm-9 pe-0">
                <%= text_field_tag :friend, params[:friend], placeholder: "Friend's name", autofocus: true, class: "form-control form-control" %>
            </div>

            <div class="col-sm-3 ps-0">
                <%= button_tag type: :submit, class: "btn btn-primary" do %>
                    <%= fa_icon "search" %>
                <% end %>
            </div>
        </div>
    <% end %>
    <%= render "friends/result" %>
    <% if !@friends.empty? %>
        <%= render 'friends/list' %>
    <% end %>
</div>
    

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class="search-area">
    <h3>
        Search Stocks
    </h3>

    <%= form_tag search_stock_path class: "form-inline" do %>
        <div class="form-group row">
            <div class="col-sm-9 pe-0">
                <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control" %>
            </div>

            <div class="col-sm-3 ps-0">
                <%= button_tag type: :submit, class: "btn btn-primary" do %>
                    <%= fa_icon "search" %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>


<%= render "users/result" %>
<%= render "stocks/list" %>

app/views/users/show.html.erb
<h2>
    User Details
</h2>

<div class="card my-2 me-2">
    <div class="card-header">
            Friend
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <strong>Name:</strong> <%= @user.full_name %>
            </li>
            <li class="list-group-item">
                <strong>Email:</strong> <%= @user.email %>
            </li>

            <li class="list-group-item d-flex align-items-center">
                <% if current_user.not_friends_with?(@user.id) %>
                    <%= button_to 'Follow friend?', 
                    friendships_path(friend: @user),
                    data: { turbo: false, turbo_method: :post }, 
                    class: 'btn btn-sm btn-warning ms-auto' %>
                <% else %>
                    <span class="badge bg-secondary">
                        You are friends
                    </span>
                <% end %>
            </li>
        </ul>
    </div>

    <% if !@tracked_stocks.empty? %>
        <%= render 'stocks/list' %>
    <% else %>
        <div class="card my-2 me-2">
            <div class="card-header">
                Stocks
            </div>
            <div class="card-body">
                <p class="card-text">
                    This user is not tracking any stocks yet.
                </p>
            </div>
        </div>
    <% end %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to the Finance Tracker App</h1>

<%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>